- name: Add PPA repos
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - python-pip
    - nodejs
    - screen
    # Complilation
    - build-essential
    - libpq-dev
    - python-dev
    - libxml2-dev
    - libxslt-dev 

- name: Install pip packages
  pip: name=virtualenv
- pip: name=virtualenvwrapper
- pip: name=supervisor version=3.0a10

- name: Configure supervisor
  sudo: yes
  shell: "{{item}}"
  with_items:
    - echo_supervisord_conf | tee /etc/supervisord.conf
    - curl -L https://gist.github.com/raw/1213031/929e578faae2ad3bcb29b03d116bcb09e1932221/supervisord.conf | tee /etc/init/supervisord.conf

- name: Start supervisor daemon
  service: name=supervisord state=started

- name: Check virtualenv existence
  stat: path=~/.virtualenvs/commcare-hq
  register: virtualenv_path

- name: Configure virtualenv
  file: path=~/.virtualenvs state=directory
  when: not virtualenv_path.stat.exists

- shell: virtualenv ~/.virtualenvs/commcare-hq --no-site-packages
  when: not virtualenv_path.stat.exists

- name: Checkout commcare-hq code
  git: repo=https://github.com/dimagi/commcare-hq.git dest=~/commcare-hq recursive=yes

- name: Update dependencies
  pip: requirements=~/commcare-hq/requirements/requirements.txt virtualenv=~/.virtualenvs/commcare-hq extra_args='--download-cache pip_cache --allow-unverified egenix-mx-base'

- name: Upload config template
  template: src=localsettings.py.j2 dest=~/commcare-hq/localsettings.py

- name: Database migrations
  shell: "{{item}}"
  with_items:
    - ~/.virtualenvs/commcare-hq/bin/python manage.py syncdb --noinput
    - ~/.virtualenvs/commcare-hq/bin/python manage.py migrate --noinput
    - ~/.virtualenvs/commcare-hq/bin/python manage.py collectstatic --noinput
  args:
    chdir: ~/commcare-hq

- name: Check if server is running
  shell: ps ax | grep runserver | wc -l
  register: process_count

- name: Start server
  shell: screen -dmS commcare-hq ~/.virtualenvs/commcare-hq/bin/python manage.py runserver 0.0.0.0:8000
  args:
    chdir: ~/commcare-hq
  when: process_count.stdout == "1"
