---
- hosts: control
  tasks:
  - name: Add PPA repo
    apt_repository: repo='ppa:rquillo/ansible' state=present

  - name: Install ansible
    apt: name=ansible state=present

  - name: Generate ssh keypair
    shell: su vagrant -c "ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''"

  - name: Retrieve public key
    fetch: src=/home/vagrant/.ssh/id_rsa.pub dest=id_rsa.pub flat=yes

- hosts: app1
  tasks:
  - name: Add authorized key
    authorized_key: user=root key="{{ lookup('file', 'id_rsa.pub') }}"

- hosts: db1
  tasks:
  - name: Add authorized key
    authorized_key: user=root key="{{ lookup('file', 'id_rsa.pub') }}"
